export const actions = {
    CHANGE_MUSIC_NAME: 'CHANGE_MUSIC_NAME',
    CHANGE_MUSIC_LENGTH: 'CHANGE_MUSIC_LENGTH',
    CHANGE_ARTISTS: 'CHANGE_ARTISTS',
    CHANGE_VOLUME: 'CHANGE_VOLUME',
    CHANGE_MUSIC_RANGE: 'CHANGE_MUSIC_RANGE'
}